export default {
    PRIMARY_COLOR_DARK: '#404040',
    SECONDARY_COLOR_DARK: '#6c6c6c',
    PRIMARY_COLOR_MED: '#ff4c04',
    SECONDARY_COLOR_MED: '#ff712f',
    PRIMARY_COLOR_LIGHT: '#ffbd86',
    SECONDARY_COLOR_LIGHT: '#fed2a4',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '500',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#f5f0eb'
  };